import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from './api/uploadthing/core';

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
	<ClerkProvider>
		<html lang="en" suppressHydrationWarning>
				<body className={cn(
					font.className,
					'bg-white dark:bg-[#313338]'
				)}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem={false}
						storageKey='chat-app-theme'
					>
						<NextSSRPlugin
							routerConfig={extractRouterConfig(ourFileRouter)}
						/>
						{children}
					</ThemeProvider>
				</body>
		</html>
	</ClerkProvider>
  )
}
